spring:
  application:
    name: gcp-pubsub-demo
  cloud:
    gcp:
      project-id: red-amarilla
application:
  pubsub:
    topic: projects/red-amarilla/topics/demo
    subscription: projects/red-amarilla/subscriptions/demo-sub